### PR TITLE
Set up Linux Github Actions Build & Add Linux Build Instructions & Update Readme

### PR DESCRIPTION
**Pull request by FeyXieXzf**
Precisely, I do the following:
- capture build artifacts for linux
- auto upload these artifacts to releases if needed
- update readme

...and some small enhancements:
- suggests in readme that Arch Linux users can install QtScrcpy from AUR

These things are tested [here](https://github.com/UjhhgtgTeams/QtScrcpy/actions/workflows/ubuntu.yml)

### CODE REVIEW

**Comment by FeyXieXzf** [comment]
I just found out that another pr is adding the arch linux suggestion, but that pr seems to...be in a mess. Thus it magically conflicts with the main branch :/

**Comment by FeyXieXzf** [comment]
Looks like it's because that fork is keep merging the new commits from the main repo, and cause that.

**Comment by FeyXieXzf** [comment]
Can some one review this?

**Comment by barry-ran** [comment]
Sorry I'm late. Great job

**Review by barry-ran — APPROVED** [review]

**Pull request merged**
